vich_uploader:
    db_driver: orm

    mappings:
        images_galerie:
            uri_prefix:         '%app.path.images_galerie%'
            upload_destination: '%kernel.project_dir%/public%app.path.images_galerie%'
        images_event:
            uri_prefix:         '%app.path.images_event%'
            upload_destination: '%kernel.project_dir%/public%app.path.images_event%'
