<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\HttpFoundation\File\File;
use Symfony\Component\Validator\Constraints as Asserts;


/**
 * @ORM\Entity(repositoryClass="App\Repository\GalerieRepository")
 * @ORM\EntityListeners({"App\EntityListener\ImageListener"})
 */
class Galerie
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * Auto generated by entity listener
     * @ORM\Column(type="string", length=255)
     */
    private $filename;

    /**
     * Auto generated by entity listener
     * @var string
     */
    private $tempFilename;

    /**
     * @var File
     * @Asserts\Image()
     * @Asserts\NotBlank()
     */
    private $file;

    /**
     * @var string|null
     */
    private $webView;

    /**
     * @ORM\Column(type="string", length=255)
     */
    public $titre;

    /**
     * @ORM\Column(type="datetime")
     */
    private $datepublication;


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitre(): ?string
    {
        return $this->titre;
    }

    public function setTitre(string $titre): self
    {
        $this->titre = $titre;

        return $this;
    }

    public function getDatePublication(): ?\DateTimeInterface
    {
        return $this->datepublication;
    }

    public function setDatePublication(\DateTimeInterface $datepublication): self
    {
        $this->datepublication = $datepublication;

        return $this;
    }

    // public function getUrlPhoto(): ?string
    // {
    //     return $this->urlphoto;
    // }

    // public function setUrlPhoto(string $urlphoto): self
    // {
    //     $this->urlphoto = $urlphoto;

    //     return $this;
    // }

    public function getFile(): ?File
    {
        return $this->file;
    }

    public function setFile(File $file = null): self
    {
        $this->file = $file;

        return $this;
    }
    
    public function setFilename(string $filename): self
    {
        $this->filename = $filename;

        return $this;
    }

    public function getFilename(): ?string
    {
        return '/assets/img/Galerie/'.$this->filename;
    }

    public function getTempFilename(): ?string
    {
        return $this->tempFilename;
    }

    public function setTempFilename($filename): self
    {
        $this->tempFilename = $filename;

        return $this;
    }

    public function getWebView(): string
    {
        return $this->webView;
    }

    public function setWebView(string $webView): self
    {
        $this->webView = $webView;

        return $this;
    }
}
