easy_admin:
    design:
        menu:
            - label: 'Administration'
              icon: 'cog'
              children:
                  - { entity: 'Evenement', icon: 'calendar-alt', label: 'Liste des évènements'}
                  - { entity: 'Galerie', icon: 'images', label: 'La galerie'}
                  - { entity: 'Carte', icon: 'utensils', label: 'La carte'}
                  - { entity: 'Horaire', icon: 'clock', label: 'Les horaires'}

