easy_admin:
  entities:
    Horaire:
      class: App\Entity\Horaire
      form:
          fields:
              - { property: 'jour' }
              - { property: 'heures' }

      list:
          fields:
              - { property: 'jour' }
              - { property: 'heures' }
